config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  resources :members, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :edit, :update, :show, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_one_attached :profile_image
       
         validates :name, presence: true, uniqueness: true, length: { in: 2..20 }

         def get_profile_image(width, height)
          unless profile_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
          end
          profile_image.variant(resize_to_limit: [width, height]).processed
        end
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
  belongs_to :member

  validates :store, presence: true
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to member_path(@member)
  end

  private

  def member_params
    params.require(:member).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.member_id = current_member.id
    if @post.save
      flash[:notice] = "レビューが投稿されました."
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿を編集しました."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
    @post = Post.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:store, :title, :star, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/homes/about.html.erb
<div class="container">
  <h2>自分好みのラーメンを見つけよう！</h2>
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <div class="btn-wrapper mx-auto col-10">
        <div class="row"><br>
          <%= link_to "ログイン", new_member_session_path, class:"btn btn-dark btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
         <%= link_to "新規登録", new_member_registration_path, class:"btn btn-danger btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
<h2>自分好みのラーメンを見つけよう！</h2>
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <div class="btn-wrapper mx-auto col-10">
        <div class="row"><br>
          <%= link_to "ログイン", new_member_session_path, class:"btn btn-dark btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
         <%= link_to "新規登録", new_member_registration_path, class:"btn btn-danger btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramendou</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/0db50f54a7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
    <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><%= image_tag('ramen.logo.png') %></a>
        <ul class="navbar-nav ml-auto">
          <% if member_signed_in? %>
          <li>
            <%= link_to root_path, class:"nav-link text-dark" do %>
              <i class="fa-solid fa-home"></i>
              トップ
            <% end %>
          </li>
          <li>
            <%= link_to member_path(current_member), class:"nav-link text-dark" do %>
              <i class="fa-solid fa-users"></i>
              マイページ
            <% end %>
          </li>
          <li>
            <%= link_to new_post_path, class:"nav-link text-dark" do %>
              <i class="fa-solid fa-pen-to-square"></i>
              レビューする
            <% end %>
          </li>
          <li>
            <%= link_to posts_path, class:"nav-link text-dark" do %>
              <i class="fa-solid fa-pen-to-square"></i>
              投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_member_session_path, class:"nav-link text-dark", method: :delete do %>
              <i class="fa-solid fa-sign-out-alt"></i>
              ログアウト
            <% end %> 
          </li>
          <% else %>
          <li>
            <%= link_to root_path, class:"nav-link text-dark" do %>
              <i class="fa-solid fa-home"></i>
              トップ
            <% end %>
          </li>

          <li>
            <%= link_to about_path, class:"nav-link text-dark" do %>
              <i class="fa-solid fa-link"></i>
              アバウト
            <% end %>
          </li>

          <li>
            <%= link_to new_member_registration_path, class:"nav-link text-dark" do %>
              <i class="fa-solid fa-user-plus"></i>
              新規登録
            <% end %>
          </li>

          <li>
            <%= link_to new_member_session_path, class:"nav-link text-dark" do %>
              <i class="fa-solid fa-sign-in-alt"></i>
              ログイン
            <% end %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @member do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/members/show.html.erb
マイページ
<!-- ユーザーの詳細 -->
<div>
  <h3><%= @member.name %></h3>
  <%= image_tag @member.get_profile_image(100,100) %>
  <% if @member == current_member %>
    <p><%= link_to "プロフィール編集", edit_member_path(@member) %></p>
  <% end %>
</div>
<%= link_to "投稿詳細", post_path(current_member) %><br>
<%= link_to "投稿一覧", posts_path %>

app/views/posts/edit.html.erb
<h2>レビュー</h2>
<% if @post.errors.any? %>
      <h3><%= @post.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>
<%= form_with model: @post, url: post_path(@post.id), method: :patch do |f| %>
  <p>
    <strong>店舗名:</strong><br>
    <%= f.text_field :store %>
  </p>
  <p>
    <strong>メニュー名:</strong><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <strong>感想:</strong><br>
    <%= f.text_area :body %>
  </p>
  <%= f.submit '投稿', class:"btn-secondary btn-danger mt-4" %>
<% end %>

app/views/posts/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h2>みんなの声</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>ニックネーム</th>
              <th>店舗名</th>
              <th>メニュー名</th>
              <th>感想</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |posts| %>
              <tr>
                <td>
                  <%=link_to(member_path(posts.member)) do %>
                    <%= image_tag posts.member.get_profile_image(100,100) %>
                  <% end %>
                </td>
                <td>
                    <%= posts.store %>
                </td>
                <td>
                    <%= posts.title %>
                </td>
                <td><%= posts.body %></td>
                <td colspan="3"></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<h2>レビュー</h2>
<% if @post.errors.any? %>
      <h3><%= @post.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>
<%= form_with model: @post do |f| %>
  <p>
    <strong>店舗名:</strong><br>
    <%= f.text_field :store %>
  </p>
  <p>
    <strong>メニュー名:</strong><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <strong>感想:</strong><br>
    <%= f.text_area :body %>
  </p>
  <%= f.submit '投稿', class:"btn-secondary btn-danger mt-4" %>
<% end %>

app/views/posts/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h2>あなたの声</h2>
        <table class="table">
          <tbody>
            <tr>
              <td><h5>会員</h5></td>
              <td><h5>店舗名</h5></td>
              <td><h5>メニュー名</h5></td>
              <td><h5>感想</h5></td>
            </tr>
            <tr>
            <td>
              <%= link_to(member_path(@post.member)) do %>
              <%= image_tag @post.member.get_profile_image(100,100) %><br>
              <%= @post.member.name %>
              <% end %>
            </td>
            <td><%= @post.store %></td>
            <td><%= @post.title %></td>
            <td><%= @post.body %></td>
            <td>
              <% if @post.member == current_member %>
                <%= link_to "編集", edit_post_path(@post), class:"btn btn-sm btn-outline-warning" %>
              <% end %>
            </td>
            <td>
              <% if @post.member == current_member %>
                <%= link_to "削除", post_path(@post), class:"btn btn-sm btn-outline-danger", method: :delete, "data-confirm" => "Are you sure?" %>
              <% end %>
            </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>